# Generated by Django 3.0.3 on 2020-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=32, null=True, verbose_name='Номер телефона'),
        ),
    ]
