# Generated by Django 3.0.3 on 2020-02-25 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='Телефон пользователя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения пользователя')),
                ('profile_picture', models.ImageField(default='uploads/profile_app/cute_kitten_face.png', null=True, upload_to='uploads/profile_app/profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('user',),
            },
        ),
    ]
