# Generated by Django 3.0.3 on 2020-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile_app/cute_kitten_face.png', null=True, upload_to='uploads/profile_app/profile_pics'),
        ),
    ]
